### ISSUE TITLE
possibly add references/examples to racket vr?

### ISSUE THREAD

**Issue by jfonte** [misslivirose/learnvr#3]
- video of Carmack demoing it https://www.youtube.com/watch?v=ydyztGZnbNs
- script samples discussion https://groups.google.com/forum/#!msg/racket-users/RFlh0o6l3Ls/8InN7uz-Mv4J (links are currently dead...)

**Comment by misslivirose** [comment]
Thanks! Added a reference in Getting Started / VrScript to be updated in more depth moving forward.

**Comment by misslivirose** [comment]
Commit a3e3e34
